### PR TITLE
Somewhat complete Beginner's Guide

### PR DESCRIPTION
**Pull request by brentonannan**
This is a beginner's guide aimed at absolute beginners, as opposed to the official beginner's guide which is a brilliant resource for those with experience developing.

This is a work in progress, not ready for merge as yet.

### CODE REVIEW

**Comment by catherine-jones** [comment]
hi @brentonannan created a WIP label and added it to our branches :)

**Comment by daphsta** [comment]
Hi @brentonannan , the beginner's guide is a very good idea because that is how RailsGirls introduces Ruby before moving onto Rails.
I was wondering that it might be helpful to do a simple introductory guide to GenServer as the `handle_in` callback is used in the app. 
Someone coming from an OO background might find GenServer a bit mysterious and confusing perhaps. 
What are your thoughts?

**Comment by catherine-jones** [comment]
@brentonannan @daphsta I think this sounds like a great idea can you open an issue and feel free to open a PR if you have time :)

**Comment by brentonannan** [comment]
Heya @daphsta. I agree that a GenServer guide would be awesome! I'd also like to see a Mix guide, an ExUnit guide, and a Mix task guide. I'll def keep trying to write guides over time, but it is quite time consuming, so this one will have to do for this weekend... I'm cutting it fine, but will be done before Friday.

Meanwhile, review notes would be greatly appreciated!

**Comment by daphsta** [comment]
hey @brentonannan @catherine-jones I can help with the guide but it would not be in time for this Friday :/ 
Thanks for your feedback by the way.

**Comment by brentonannan** [comment]
@catherine-jones I'm going to ship this as-is; I want to add a `Modules and Functions` section, but have just been overwhelmingly busy. If I get a chance to add something today, I will.

**Pull request merged**
